import test from "node:test";
import assert from "node:assert/strict";
import { coordinateJournalAppend } from "../../src/core/journal-append-coordination/coordinator.js";
import { JOURNAL_APPEND_REQUEST_SCHEMA } from "../../src/core/journal-append-coordination/contract.js";
import { createOperationLedger } from "../../src/core/runtime-contract/ledger.js";
import { coordinateWorkspaceProjectionReconciliation, recordReconciliationEffects } from "../../src/core/workspace-projection-reconciliation/coordinator.js";
import { createReconciliationResult } from "../../src/core/workspace-projection-reconciliation/contract.js";
import { captureWorkspaceProjectionSnapshot, createReconciliationPlan } from "../../src/core/workspace-projection-reconciliation/planner.js";
import { createReconciliationScheduler } from "../../src/core/workspace-projection-reconciliation/scheduler.js";

const NOW="2026-07-13T10:00:00.000Z",LATER="2026-07-13T10:01:00.000Z";
const copy=(value)=>JSON.parse(JSON.stringify(value));
function tab(id="tab-a",overrides={}){return{workspaceTabId:id,alias:"Alias "+id,role:"Role",firstSeenAt:NOW,pinned:true,unknownTab:{keep:true},tabId:id==="tab-a"?1:2,tabKey:"https://"+id+".test::"+id,windowId:1,groupId:-1,index:id==="tab-a"?0:1,url:"https://"+id+".test",displayUrl:id+".test",originalTitle:id,isOpen:true,lastMatchStatus:"exact_tab_id",lastSeenAt:NOW,...overrides};}
function workspace(overrides={}){return{workspaceId:"ws-1",workspaceRevision:0,name:"Workspace",aim:"Aim",workspaceType:"research",journal:[],timeline:[{eventId:"old"}],tabs:[tab()],unknownWorkspace:{keep:true},...overrides};}
function liveFor(item,overrides={}){return{id:item.tabId,windowId:item.windowId,groupId:item.groupId,index:item.index,url:item.url,title:item.originalTitle,...overrides};}
function requestFor(observed,browserTabs,{operationId="reconcile-1",triggers=["tab_updated"],contextId="worker-1"}={}){const captured=captureWorkspaceProjectionSnapshot(observed,NOW);assert.equal(captured.valid,true);return{schema:"constellation-workspace-projection-reconcile-v0.1",operationId,contextId,workspaceId:observed.workspaceId,requestedAt:NOW,payload:createReconciliationPlan(captured.snapshot,browserTabs,{operationId,triggers,reconciledAt:LATER})};}
function compatibilityRead(store){const canonicalPresent=store.canonical!==undefined,legacyPresent=store.legacy!==undefined,canonicalValue=canonicalPresent?copy(store.canonical):undefined,legacyValue=legacyPresent?copy(store.legacy):undefined,equivalent=canonicalPresent&&legacyPresent&&JSON.stringify(canonicalValue)===JSON.stringify(legacyValue);return{canonicalPresent,legacyPresent,canonicalValue,legacyValue,equivalent,conflict:canonicalPresent&&legacyPresent&&!equivalent,value:canonicalPresent?canonicalValue:legacyValue};}
function serialLock(){let tail=Promise.resolve();const events=[];return{events,request(name,callback){const wait=tail;let release;tail=new Promise((resolve)=>release=resolve);return wait.then(async()=>{events.push("enter:"+name);try{return await callback();}finally{events.push("leave:"+name);release();}});}};}
function reconciliationFake(initial,{lock=serialLock(),canonical=true,legacy=true,writeFail=false,verification="normal"}={}){const store={canonical:canonical?copy(initial):undefined,legacy:legacy?copy(initial):undefined},events=[];return{store,events,lock,adapters:{withRuntimeStateLock:(name,callback)=>lock.request(name,callback),readLatestActiveWorkspace:async()=>{events.push("read");const readCount=events.filter((event)=>event==="read").length;if((verification==="read_fail"&&events.includes("write"))||(verification==="no_change_read_fail"&&readCount===2))throw new Error("read failed");const read=compatibilityRead(store);if((verification==="mismatch"&&events.includes("write"))||(verification==="no_change_mismatch"&&readCount===2)){read.legacyValue={...read.legacyValue,name:"mismatch"};read.equivalent=false;read.conflict=true;}return read;},writeCompatibleActiveWorkspace:async(value)=>{events.push("write");if(writeFail)throw new Error("write failed");store.canonical=copy(value);store.legacy=copy(value);}}};}
function journalRequest(operationId="journal-1"){return{schema:JOURNAL_APPEND_REQUEST_SCHEMA,operationId,contextId:"panel-1",workspaceId:"ws-1",requestedAt:NOW,entry:{entryId:"entry-1",text:"Journal survives",tag:"",relatedRoleId:"",relatedRoleLabel:"",createdAt:NOW}};}
function journalAdapters(store,lock){let ledger=createOperationLedger();return{withRuntimeStateLock:(name,callback)=>lock.request(name,callback),readLatestActiveWorkspace:async()=>compatibilityRead(store),writeCompatibleActiveWorkspace:async(value)=>{store.canonical=copy(value);store.legacy=copy(value);},verifyCompatibleActiveWorkspace:async(expected,entry)=>{const read=compatibilityRead(store);return read.canonicalPresent&&read.legacyPresent&&read.equivalent&&JSON.stringify(read.value)===JSON.stringify(expected)&&read.value.journal.filter((item)=>item.entryId===entry.entryId).length===1;},readOperationLedger:async()=>copy(ledger),writeOperationLedger:async(value)=>{ledger=copy(value);},now:()=>LATER};}

test("journal and reconciliation both survive a same-revision start with journal authority first",async()=>{const original=workspace(),lock=serialLock(),fake=reconciliationFake(original,{lock}),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);const journal=coordinateJournalAppend(journalRequest(),journalAdapters(fake.store,lock));const reconciliation=coordinateWorkspaceProjectionReconciliation(request,fake.adapters);const[journalResult,reconciliationResult]=await Promise.all([journal,reconciliation]);assert.equal(journalResult.status,"committed");assert.equal(reconciliationResult.status,"committed");assert.equal(fake.store.canonical.workspaceRevision,2);assert.equal(fake.store.canonical.journal.length,1);assert.equal(fake.store.canonical.tabs[0].index,1);assert.deepEqual(fake.store.canonical,fake.store.legacy);});
test("reconciliation authority first is preserved by waiting journal",async()=>{const original=workspace(),lock=serialLock(),fake=reconciliationFake(original,{lock}),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);const reconciliation=coordinateWorkspaceProjectionReconciliation(request,fake.adapters);const journal=coordinateJournalAppend(journalRequest(),journalAdapters(fake.store,lock));const[reconciliationResult,journalResult]=await Promise.all([reconciliation,journal]);assert.equal(reconciliationResult.status,"committed");assert.equal(journalResult.status,"committed");assert.equal(fake.store.canonical.workspaceRevision,2);assert.equal(fake.store.canonical.tabs[0].index,1);assert.equal(fake.store.canonical.timeline.filter((item)=>item.type==="workspace_tabs_refreshed").length,1);assert.equal(fake.store.canonical.journal.length,1);});
test("journal committed after browser snapshot survives latest-state reconciliation",async()=>{const original=workspace(),lock=serialLock(),fake=reconciliationFake(original,{lock}),request=requestFor(original,[liveFor(original.tabs[0],{index:2})]);await coordinateJournalAppend(journalRequest(),journalAdapters(fake.store,lock));const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"committed");assert.equal(fake.store.canonical.workspaceRevision,2);assert.equal(fake.store.canonical.journal[0].entryId,"entry-1");});
test("multi-tab reconciliation increments revision once and preserves user and unknown fields",async()=>{const original=workspace({tabs:[tab("tab-a"),tab("tab-b")]}),fake=reconciliationFake(original),request=requestFor(original,[liveFor(original.tabs[0],{index:3}),liveFor(original.tabs[1],{windowId:2})]);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"committed");assert.equal(result.recordsChanged,2);assert.equal(fake.store.canonical.workspaceRevision,1);assert.equal(fake.store.canonical.timeline.filter((item)=>item.type==="workspace_tabs_refreshed").length,1);assert.deepEqual(fake.store.canonical.unknownWorkspace,original.unknownWorkspace);assert.equal(fake.store.canonical.tabs[0].alias,original.tabs[0].alias);assert.equal(fake.store.canonical.tabs[0].role,original.tabs[0].role);assert.equal(fake.store.canonical.tabs[0].pinned,true);assert.equal(Object.hasOwn(fake.store.canonical.tabs[0],"candidateCount"),false);});
test("tab added after snapshot remains completely untouched",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]),added=tab("tab-new",{custom:"untouched"}),latest=workspace({workspaceRevision:1,tabs:[original.tabs[0],added]}),fake=reconciliationFake(latest);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"committed");assert.deepEqual(fake.store.canonical.tabs[1],added);assert.equal(fake.store.canonical.workspaceRevision,2);});
test("latest tabs with missing or malformed workspaceTabId fail closed",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);for(const invalidTab of[{alias:"missing"},{workspaceTabId:42,alias:"malformed"}]){const latest=workspace({workspaceRevision:1,tabs:[original.tabs[0],invalidTab]}),fake=reconciliationFake(latest),result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"rejected");assert.equal(result.reason,"invalid_workspace_tab_identity");assert.equal(fake.events.includes("write"),false);assert.deepEqual(fake.store.canonical,latest);}});
test("duplicate valid workspaceTabIds in latest state fail closed",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]),latest=workspace({workspaceRevision:1,tabs:[original.tabs[0],tab("tab-a",{alias:"duplicate"})]}),fake=reconciliationFake(latest),result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"rejected");assert.equal(result.reason,"duplicate_workspace_tab_id");assert.equal(fake.events.includes("write"),false);assert.deepEqual(fake.store.canonical,latest);});
test("tab removed after snapshot is skipped and never recreated",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]),latest=workspace({workspaceRevision:1,tabs:[]}),fake=reconciliationFake(latest);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"no_change");assert.deepEqual(fake.store.canonical.tabs,[]);assert.equal(fake.events.includes("write"),false);});
test("active workspace identity change aborts without write",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]),fake=reconciliationFake(workspace({workspaceId:"ws-2"}));const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"workspace_conflict");assert.equal(result.reason,"workspace_id_mismatch");assert.equal(fake.events.includes("write"),false);});
test("stale projection baseline rejects and older plan cannot regress newer commit",async()=>{const original=workspace(),older=requestFor(original,[liveFor(original.tabs[0],{index:1})],{operationId:"older"}),newer=requestFor(original,[liveFor(original.tabs[0],{index:2})],{operationId:"newer"}),fake=reconciliationFake(original);assert.equal((await coordinateWorkspaceProjectionReconciliation(newer,fake.adapters)).status,"committed");const result=await coordinateWorkspaceProjectionReconciliation(older,fake.adapters);assert.equal(result.status,"rejected");assert.equal(result.reason,"projection_baseline_changed");assert.equal(fake.store.canonical.tabs[0].index,2);assert.equal(fake.store.canonical.workspaceRevision,1);});
test("a genuine change repairs a missing canonical or legacy peer and verifies both",async()=>{for(const options of[{canonical:false},{legacy:false}]){const original=workspace(),fake=reconciliationFake(original,options),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"committed");assert.equal(result.workspaceVerified,true);assert.deepEqual(fake.store.canonical,fake.store.legacy);}});
test("missing peer plus semantic no-change returns compatible_peer_missing without repair",async()=>{const original=workspace(),fake=reconciliationFake(original,{canonical:false}),request=requestFor(original,[liveFor(original.tabs[0])]);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"workspace_conflict");assert.equal(result.reason,"compatible_peer_missing");assert.equal(result.workspaceCommitted,false);assert.equal(fake.events.includes("write"),false);assert.equal(fake.store.canonical,undefined);});
test("divergent peers fail closed",async()=>{const original=workspace(),fake=reconciliationFake(original);fake.store.legacy.name="divergent";const result=await coordinateWorkspaceProjectionReconciliation(requestFor(original,[liveFor(original.tabs[0],{index:1})]),fake.adapters);assert.equal(result.reason,"compatibility_conflict");assert.equal(fake.events.includes("write"),false);});
test("both peers absent report active_workspace_missing",async()=>{const original=workspace(),fake=reconciliationFake(original,{canonical:false,legacy:false}),result=await coordinateWorkspaceProjectionReconciliation(requestFor(original,[liveFor(original.tabs[0],{index:1})]),fake.adapters);assert.equal(result.status,"failed");assert.equal(result.reason,"active_workspace_missing");assert.equal(result.workspaceCommitted,false);});
test("persistence rejection and verification failures report phase honestly",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);const write=reconciliationFake(original,{writeFail:true}),writeResult=await coordinateWorkspaceProjectionReconciliation(request,write.adapters);assert.equal(writeResult.reason,"workspace_write_failed");assert.equal(writeResult.workspaceCommitted,false);assert.equal(writeResult.workspaceVerified,false);const read=reconciliationFake(original,{verification:"read_fail"}),readResult=await coordinateWorkspaceProjectionReconciliation(request,read.adapters);assert.equal(readResult.reason,"workspace_verification_read_failed");assert.equal(readResult.workspaceCommitted,true);assert.equal(readResult.workspaceVerified,false);const verify=reconciliationFake(original,{verification:"mismatch"}),verifyResult=await coordinateWorkspaceProjectionReconciliation(request,verify.adapters);assert.equal(verifyResult.reason,"workspace_verification_failed");assert.equal(verifyResult.workspaceCommitted,true);assert.equal(verifyResult.workspaceVerified,false);assert.equal(verifyResult.authorityPhase,"workspace_write_returned");});
test("semantic no-change performs two compatible reads and zero workspace writes or evidence",async()=>{const original=workspace(),fake=reconciliationFake(original),request=requestFor(original,[liveFor(original.tabs[0])]);const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"no_change");assert.equal(result.reason,"projection_current");assert.equal(result.workspaceVerified,true);assert.equal(fake.events.filter((event)=>event==="read").length,2);assert.equal(fake.events.includes("write"),false);assert.deepEqual(fake.store.canonical,original);});
test("no-change verification read failure and mismatch are reported honestly",async()=>{const original=workspace(),request=requestFor(original,[liveFor(original.tabs[0])]);const readFailure=reconciliationFake(original,{verification:"no_change_read_fail"}),readResult=await coordinateWorkspaceProjectionReconciliation(request,readFailure.adapters);assert.equal(readResult.status,"failed");assert.equal(readResult.reason,"workspace_verification_read_failed");assert.equal(readResult.workspaceCommitted,false);assert.equal(readResult.workspaceVerified,false);assert.equal(readFailure.events.includes("write"),false);const mismatch=reconciliationFake(original,{verification:"no_change_mismatch"}),mismatchResult=await coordinateWorkspaceProjectionReconciliation(request,mismatch.adapters);assert.equal(mismatchResult.status,"failed");assert.equal(mismatchResult.reason,"workspace_verification_failed");assert.equal(mismatchResult.workspaceCommitted,false);assert.equal(mismatchResult.workspaceVerified,false);assert.equal(mismatch.events.includes("write"),false);});
test("semantic retry with a new execution identity appends no duplicate evidence",async()=>{const original=workspace(),fake=reconciliationFake(original),browser=[liveFor(original.tabs[0],{index:1})],first=await coordinateWorkspaceProjectionReconciliation(requestFor(original,browser,{operationId:"first"}),fake.adapters);assert.equal(first.status,"committed");const latest=copy(fake.store.canonical),retry=await coordinateWorkspaceProjectionReconciliation(requestFor(latest,browser,{operationId:"retry"}),fake.adapters);assert.equal(retry.status,"no_change");assert.equal(fake.store.canonical.timeline.filter((item)=>item.type==="workspace_tabs_refreshed").length,1);assert.equal(fake.store.canonical.workspaceRevision,1);});
test("malformed plans reject without mutation",async()=>{const original=workspace(),fake=reconciliationFake(original),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]);request.payload.patches.push(copy(request.payload.patches[0]));const result=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);assert.equal(result.status,"rejected");assert.equal(result.reason,"invalid_request");assert.equal(fake.events.length,0);assert.deepEqual(fake.store.canonical,original);});
test("equivalent trigger sets produce equivalent deterministic evidence",async()=>{const original=workspace(),one=reconciliationFake(original),two=reconciliationFake(original),browser=[liveFor(original.tabs[0],{index:1})],a=requestFor(original,browser,{operationId:"same",triggers:["tab_updated","tab_moved","tab_updated"]}),b=requestFor(original,browser,{operationId:"same",triggers:["tab_moved","tab_updated"]});await coordinateWorkspaceProjectionReconciliation(a,one.adapters);await coordinateWorkspaceProjectionReconciliation(b,two.adapters);assert.deepEqual(one.store.canonical,two.store.canonical);});
test("diagnostic or notification failure does not change a verified commit",async()=>{const original=workspace(),fake=reconciliationFake(original),request=requestFor(original,[liveFor(original.tabs[0],{index:1})]),committed=await coordinateWorkspaceProjectionReconciliation(request,fake.adapters);const diagnostic=await recordReconciliationEffects(committed,{appendDiagnostic:async()=>{throw new Error("diagnostic")},sendNotification:async()=>{}});assert.equal(diagnostic.status,"committed");assert.equal(diagnostic.workspaceVerified,true);assert.deepEqual(diagnostic.warnings,["diagnostic_write_failed"]);const notification=await recordReconciliationEffects(committed,{appendDiagnostic:async()=>{},sendNotification:async()=>{throw new Error("notification")}});assert.equal(notification.status,"committed");assert.equal(notification.workspaceVerified,true);assert.deepEqual(notification.warnings,["notification_failed"]);});
test("post-lock diagnostic and notification policy is bounded by outcome and startup trigger",async()=>{const attempted=async(result,options)=>{const calls=[];const output=await recordReconciliationEffects(result,{appendDiagnostic:async()=>calls.push("diagnostic"),sendNotification:async()=>calls.push("notification")},options);return{calls,output};},base=(status,reason=null,triggers=["tab_updated"],workspaceId="ws-1")=>createReconciliationResult({operationId:"effect-"+status,workspaceId},status,{reason,triggers,workspaceVerified:status==="committed"||status==="no_change",workspaceCommitted:status==="committed",warnings:[],phase:"lock_released",authorityPhase:"workspace_verified"});let observed=await attempted(base("committed"));assert.deepEqual(observed.calls,["diagnostic","notification"]);assert.equal(observed.output.diagnosticRecorded,true);assert.equal(observed.output.notificationSent,true);for(const trigger of["extension_installed","extension_startup","sidepanel_startup"]){observed=await attempted(base("no_change","projection_current",[trigger]));assert.deepEqual(observed.calls,["diagnostic"]);}observed=await attempted(base("no_change","projection_current"));assert.deepEqual(observed.calls,[]);for(const [status,reason]of[["workspace_conflict","workspace_id_mismatch"],["rejected","invalid_request"],["failed","workspace_verification_failed"]]){observed=await attempted(base(status,reason));assert.deepEqual(observed.calls,["diagnostic"]);}observed=await attempted(base("failed","active_workspace_missing",["extension_startup"],""),{reconciliationStarted:false});assert.deepEqual(observed.calls,[]);assert.equal(observed.output.status,"failed");observed=await attempted(base("workspace_conflict","compatibility_conflict"),{reconciliationStarted:false});assert.deepEqual(observed.calls,[]);});

test("production planner gives exact tab ID precedence over URL fallback",()=>{const source=workspace(),captured=captureWorkspaceProjectionSnapshot(source,NOW).snapshot,browser=[liveFor(source.tabs[0],{id:99}),liveFor(source.tabs[0],{id:source.tabs[0].tabId,title:"exact"})],plan=createReconciliationPlan(captured,browser,{operationId:"planner-exact",triggers:["tab_updated"],reconciledAt:LATER});assert.equal(plan.patches[0].projection.tabId,source.tabs[0].tabId);assert.equal(plan.patches[0].projection.lastMatchStatus,"exact_tab_id");});
test("production planner leaves repeated unresolved URLs ambiguous",()=>{const shared="https://shared.test",source=workspace({tabs:[tab("tab-a",{tabId:10,url:shared}),tab("tab-b",{tabId:11,url:shared})]}),captured=captureWorkspaceProjectionSnapshot(source,NOW).snapshot,plan=createReconciliationPlan(captured,[{id:20,windowId:1,groupId:-1,index:0,url:shared,title:"shared"}],{operationId:"planner-ambiguous",triggers:["tab_updated"],reconciledAt:LATER});assert.deepEqual(plan.patches.map((patch)=>patch.projection.lastMatchStatus),["ambiguous_url_matches","ambiguous_url_matches"]);assert.deepEqual(plan.patches.map((patch)=>patch.projection.isOpen),[false,false]);});
test("production planner uses single URL fallback only for one unresolved match",()=>{const source=workspace({tabs:[tab("tab-a",{tabId:10})]}),captured=captureWorkspaceProjectionSnapshot(source,NOW).snapshot,plan=createReconciliationPlan(captured,[{id:20,windowId:2,groupId:-1,index:0,url:source.tabs[0].url,title:"fallback"}],{operationId:"planner-fallback",triggers:["tab_updated"],reconciledAt:LATER});assert.equal(plan.patches[0].projection.tabId,20);assert.equal(plan.patches[0].projection.lastMatchStatus,"single_url_fallback");});

function fakeTimers(){let next=1;const timers=new Map();return{setTimer(callback){const id=next++;timers.set(id,callback);return id;},clearTimer(id){timers.delete(id);},fire(){const entries=[...timers.entries()];timers.clear();for(const[,callback]of entries)callback();},count(){return timers.size;}};}
test("coalesced triggers execute once with normalized identities",async()=>{const timers=fakeTimers(),calls=[],scheduler=createReconciliationScheduler({setTimer:timers.setTimer,clearTimer:timers.clearTimer,execute:async(context)=>calls.push(context),debounceMs:220});scheduler.schedule("tab_updated");scheduler.schedule("tab_moved");scheduler.schedule("tab_updated");assert.equal(timers.count(),1);timers.fire();await scheduler.whenIdle();assert.deepEqual(calls,[{triggers:["tab_moved","tab_updated"]}]);});
test("trigger during execution schedules at most one later convergence run",async()=>{const timers=fakeTimers(),calls=[];let release;const gate=new Promise((resolve)=>release=resolve),scheduler=createReconciliationScheduler({setTimer:timers.setTimer,clearTimer:timers.clearTimer,execute:async(context)=>{calls.push(context);if(calls.length===1)await gate;},debounceMs:220});scheduler.schedule("first");timers.fire();await Promise.resolve();scheduler.schedule("second");scheduler.schedule("third");timers.fire();scheduler.schedule("fourth");timers.fire();assert.equal(calls.length,1);release();await scheduler.whenIdle();assert.deepEqual(calls,[{triggers:["first"]},{triggers:["fourth","second","third"]}]);});
test("worker termination before debounce loses only unexecuted work",async()=>{const timers=fakeTimers(),calls=[],scheduler=createReconciliationScheduler({setTimer:timers.setTimer,clearTimer:timers.clearTimer,execute:async(context)=>calls.push(context),debounceMs:220});scheduler.schedule("tab_updated");scheduler.dispose();timers.fire();await scheduler.whenIdle();assert.deepEqual(calls,[]);});
